### ISSUE TITLE
时区bug

### ISSUE THREAD

**Issue by beautyOfProgram** [xiaohuilam/aliyun-mqs-php-library#1]
`
    private static function _getGMTDate(){
        date_default_timezone_set("UTC");
        return date('D, d M Y H:i:s', time()) . ' GMT';
    }
`
此处会导致调用者的时区发生变更，导致后面时间记录错误

**Comment by xiaohuilam** [comment]
I am preparing to get ready to fix this issue.

Thanks a lot.

**Comment by xiaohuilam** [comment]
Fixed in commit#8a0d3b1b06142034424a2e926b843df4b77e09b4

**Comment by beautyOfProgram** [comment]
作者更新也太及时了，哈哈
