### ISSUE TITLE
这个sdk目前有在生产环境使用吗？

### ISSUE THREAD

**Issue by 2liang** [xiaohuilam/aliyun-mqs-php-library#2]
你好，我想在php端使用阿里云的消息队列服务，官方没有提供sdk，看到你这边有，想交流一下，可以给个微信或者邮箱吗

**Comment by xiaohuilam** [comment]
这个代码已经很久没有更新了。
然后有无生产使用的案例我也不清楚了。。。

**Comment by 2liang** [comment]
可以有微信或者邮件交流一下吗

**Comment by 2liang** [comment]
unstring@163.com  我的邮箱
